# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0002_auto_20160316_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsad',
            options={'ordering': ['-id']},
        ),
    ]
