# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0003_auto_20160328_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aljazeeraad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reutersad',
            options={'ordering': ['-id']},
        ),
    ]
