# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160318_1855'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
    ]
