# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:03
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
